name: Handbook

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: handbook-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: jdx/mise-action@v2
        with:
            experimental: true
      - run: mise run install
      - run: mise run build